// C++ barcode parsing utilities implementation for Smile POS
#include "barcode_parser.h"
#include <algorithm>
#include <cctype>

std::string BarcodeParser::cleanRawInput(const std::string& rawInput) {
    std::string cleaned = rawInput;
    
    // Remove leading/trailing whitespaces, tabs, or carriage returns (\r, \n) commonly generated by scanners
    cleaned.erase(cleaned.begin(), std::find_if(cleaned.begin(), cleaned.end(), [](unsigned char ch) {
        return !std::isspace(ch);
    }));
    cleaned.erase(std::find_if(cleaned.rbegin(), cleaned.rend(), [](unsigned char ch) {
        return !std::isspace(ch);
    }).base(), cleaned.end());

    // Filter non-printable ASCII prefix control tags (e.g. STX, ESC)
    cleaned.erase(std::remove_if(cleaned.begin(), cleaned.end(), [](unsigned char ch) {
        return ch < 32 || ch > 126;
    }), cleaned.end());

    return cleaned;
}

bool BarcodeParser::isValidBarcode(const std::string& barcode) {
    if (barcode.empty()) return false;
    
    // Check if the barcode only contains alphanumeric digits
    return std::all_of(barcode.begin(), barcode.end(), [](unsigned char ch) {
        return std::isalnum(ch);
    }) && (barcode.length() >= 4 && barcode.length() <= 32);
}

std::string BarcodeParser::extractSku(const std::string& compositeInput) {
    std::string cleaned = cleanRawInput(compositeInput);
    if (!isValidBarcode(cleaned)) {
        return "";
    }
    
    // If scanning composite barcodes containing a price code suffix, extract the base SKU
    if (cleaned.length() > 7 && cleaned.rfind("SMILE", 0) == 0) {
        return cleaned.substr(0, 8);
    }
    return cleaned;
}
